
    const evidence=[
      {id:1,title:"Kamera kaydı · 15.42",text:"Mert 3B'ye elinde mavi bir dosyayla giriyor. Kamera sarı etiketi göstermiyor.",fact:true},
      {id:2,title:"Görev kaydı · 15.40",text:"Öğretmenin görev kaydında, Mert’in dün 15.40’ta proje kartlarını teslim alıp 3A’dan ayrıldığı yazıyor. Görevi kartları 3B’ye götürmek.",fact:true},
      {id:3,title:"Buluntu formu · 08.10",text:"Sarı yıldız etiketli dosya ertesi sabah 3B'nin materyal dolabında bulunmuş.",fact:true},
      {id:4,title:"Masa fotoğrafı · 15.35",text:"3A masasındaki fotoğrafta iki mavi dosya görülüyor: biri sarı yıldızlı, biri etiketsiz.",fact:true},
      {id:5,title:"Hava raporu",text:"Okulun hava istasyonunda dün saat 15.00'te yağmur yağdığı kaydedilmiş.",fact:false},
      {id:6,title:"Elif hakkında yorum",text:"Elif fotoğrafına üzülmüştü; kesin dosyayı o sakladı.",fact:false},
      {id:7,title:"Koridor söylentisi",text:"Bir öğrenci, 3B kapısının sertçe kapandığını birinden duymuş.",fact:false},
      {id:8,title:"Mert hakkında yorum",text:"Mert hızlı yürüyordu; dosyayı bilerek saklamış olmalı.",fact:false}
    ];
    const events=["Ertesi sabah 08.10: Sarı yıldızlı dosya 3B dolabında bulundu.","Dün 15.35: Sema Öğretmen dosyayı 3A masasının üstüne bıraktı.","Dün 15.40: Mert proje kartlarını teslim alıp 3A’dan ayrıldı.","Dün 15.42: Mert elinde mavi bir dosyayla 3B’ye girdi."];
    const eventOrder=[1,2,3,0];
    const langQs=[
      {q:"“Mert kartları toplayıp 3A'dan ayrıldı.” cümlesinde -(y)Ip hangi ilişkiyi kuruyor?",name:"l1",a:["Birbirini izleyen iki eylem","Eylemin yapılma biçimi","Tekrar edilen eylem"],correct:0},
      {q:"“Mert elindeki mavi dosyayı taşıyarak 3B'ye girdi.” cümlesinde -(y)ArAk neyi anlatıyor?",name:"l2",a:["Dosyayı ne zaman bulduklarını","3B'ye nasıl girdiğini","Dosyayı kimin sakladığını"],correct:1},
      {q:"“Öğrenciler dolapları araya araya dosyayı buldu.” cümlesinde -A -A neyi vurguluyor?",name:"l3",a:["Arama işinin tekrarlandığını","Dolabın kilitli olduğunu","Dosyanın kimde olduğunu"],correct:0}
    ];

let score=0,current=0,unlocked=0,awarded={};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function feedback(id,ok,text){const el=$(id);el.className=`feedback show ${ok?'good':'bad'}`;el.textContent=text;el.setAttribute('role','status')}
function add(points,key){if(!awarded[key]){score+=points;awarded[key]=true;$('#score').textContent=score}}
function go(n){if(n>unlocked)return;current=n;$$('.stage').forEach((x,i)=>x.classList.toggle('active',i===n));$$('.mission').forEach((x,i)=>{x.classList.toggle('active',i===n);x.classList.toggle('done',!!awarded[['evidence','hyp','time','lang','report'][i]]);x.disabled=i>unlocked;x.setAttribute('aria-current',i===n?'step':'false')});$('#playArea').scrollIntoView({behavior:'smooth'})}
function ready(n,id){unlocked=Math.max(unlocked,n);$$('.mission').forEach((b,i)=>b.disabled=i>unlocked);const btn=document.getElementById(id+'Continue');btn.hidden=false}
['evidenceFeedback','hypFeedback','timeFeedback','langFeedback'].forEach((id,i)=>{const b=document.createElement('button');b.id=id+'Continue';b.className='continue-stage';b.type='button';b.hidden=true;b.textContent='Açıklamayı okudum · Devam et / Continue →';b.onclick=()=>go(i+1);$('#'+id).after(b)});
$('#start').onclick=()=>{$('#intro').hidden=true;$('#playArea').hidden=false;$('.score').hidden=false;go(0)};
$$('.mission').forEach((b,i)=>{b.disabled=i>0;b.onclick=()=>go(i)});$$('[data-prev]').forEach(b=>b.onclick=()=>go(current-1));
// Mix relevant facts with opinions; do not reveal the answer through card order.
[5,1,6,2,8,3,4,7].map(id=>evidence.find(e=>e.id===id)).forEach((e,i)=>{
  $('#evidenceGrid').insertAdjacentHTML('beforeend',`<button type="button" class="evidence" aria-pressed="false" data-id="${e.id}"><small>Kart ${i+1}</small><h3>${e.title}</h3><p>${e.text}</p></button>`);
});
$$('.evidence').forEach(x=>x.onclick=()=>{if(!x.classList.contains('selected')&&$$('.evidence.selected').length>=4){feedback('#evidenceFeedback',false,'Dört kart seçtin. Değiştirmek için önce seçili bir karta tekrar tıkla. / Deselect one card before choosing another.');return}x.classList.toggle('selected');x.setAttribute('aria-pressed',String(x.classList.contains('selected')));$('#picked').textContent=$$('.evidence.selected').length;$('#evidenceFeedbackContinue').hidden=true;$('#evidenceFeedback').className='feedback'});
langQs.forEach((q,i)=>$('#languageQuestions').insertAdjacentHTML('beforeend',`<div class="question"><b>${i+1}. ${q.q}</b><div class="options">${q.a.map((a,j)=>`<label class="option"><input type="radio" name="${q.name}" value="${j}"><span>${a}</span></label>`).join('')}</div></div>`));
events.forEach((_,i)=>$('#timeline').insertAdjacentHTML('beforeend',`<label class="time-row"><span>${i+1}.</span><select data-time aria-label="${i+1}. olay / event"><option value="">Olay seç… / Choose an event</option>${events.map((e,j)=>`<option value="${j}">${e}</option>`).join('')}</select></label>`));
$('#checkEvidence').onclick=()=>{const ids=[...$$('.evidence.selected')].map(x=>+x.dataset.id);if(ids.length!==4)return feedback('#evidenceFeedback',false,'Dört kart seç. Kartı kaldırmak için tekrar tıkla. / Select four cards; click again to deselect.');const wrong=ids.filter(id=>!evidence.find(e=>e.id===id).fact);if(wrong.length)return feedback('#evidenceFeedback',false,`${wrong.length} seçimini yeniden düşün. Hava bilgisi gerçek olabilir ama dosyanın yerini açıklamaz. Yorum ve söylenti de doğrudan kanıt değildir. / Reconsider ${wrong.length} selections: look for relevant, verifiable facts.`);add(20,'evidence');feedback('#evidenceFeedback',true,'Doğru: fotoğraf, görev kaydı, kamera ve buluntu formu. Hava raporu ilgisiz; diğer kartlar yorum veya söylenti. / Correct: the photo, task record, camera and discovery record are useful evidence.');ready(1,'evidenceFeedback')};
$('#checkHyp').onclick=()=>{const h=$('input[name=hyp]:checked'),w=$('input[name=why]:checked');if(!h||!w)return feedback('#hypFeedback',false,'İki soruya da cevap ver. / Answer both questions.');if(h.value!=='b')return feedback('#hypFeedback',false,'1. soruyu yeniden düşün: 3B’ye gitme görevi kimde? Kamera kimi gösteriyor? / Question 1: who had a task in 3B and appears on camera?');if(w.value!=='a')return feedback('#hypFeedback',false,'2. soruyu yeniden düşün: Kamerada iki mavi dosyayı ayıran işaret görünüyor mu? / Question 2: can you see the mark that distinguishes the folders?');add(20,'hyp');feedback('#hypFeedback',true,'Mert’in dosyayı kartlarla birlikte götürmesi kanıtlara en uygun açıklama. Ama etiket görünmüyor; bu kesin bilgi değil. / This explanation fits best, but the missing sticker detail leaves uncertainty.');ready(2,'hypFeedback')};
$('#checkTime').onclick=()=>{const values=[...$$('[data-time]')].map(x=>x.value);if(values.includes(''))return feedback('#timeFeedback',false,'Dört sırayı da doldur. / Fill all four positions.');if(new Set(values).size!==4)return feedback('#timeFeedback',false,'Aynı olayı iki kez seçtin. Her olayı bir kez kullan. / Use each event only once.');if(!values.every((v,i)=>+v===eventOrder[i]))return feedback('#timeFeedback',false,'Önce günlere, sonra saatlere bak. “Ertesi sabah” dünden önce mi, sonra mı? / Check the day before comparing times. Is the next morning before or after yesterday?');add(20,'time');feedback('#timeFeedback',true,'Doğru: masaya bırakma → kartları toplama → 3B’ye giriş → ertesi sabah bulma. Dosyanın dolaba bırakıldığı anı görmüyoruz. / The sequence is correct, but we did not see who put the folder in the cupboard.');ready(3,'timeFeedback')};
$('#checkLang').onclick=()=>{const wrong=langQs.map((q,i)=>{const x=$(`input[name=${q.name}]:checked`);return !x||+x.value!==q.correct?i+1:null}).filter(Boolean);if(wrong.length)return feedback('#langFeedback',false,`${wrong.join(', ')}. soruyu yeniden incele. İpucu: önce–sonra, nasıl, tekrar. / Revisit question(s) ${wrong.join(', ')}: sequence, manner, repetition.`);add(20,'lang');feedback('#langFeedback',true,'toplayıp: önce topladı, sonra ayrıldı. taşıyarak: dosyayı elinde taşıdı; bu, nasıl girdiğini anlatır. araya araya: aramayı sürdürdüler. / Sequence, manner and repeated action.');ready(4,'langFeedback')};
['hypFeedback','timeFeedback','langFeedback'].forEach((id,i)=>{document.querySelectorAll('.stage')[i+1].addEventListener('change',()=>{$('#'+id+'Continue').hidden=true;$('#'+id).className='feedback'})});
function updatePreview(){const c=$('#conclusion').value,r=$('#reason').value,l=$('#limitation').value,t=$('#ownSentence').value.trim();$('#preview').textContent=c&&r&&l?`${c}. Çünkü ${r}. ${l.charAt(0).toLocaleUpperCase('tr')+l.slice(1)}.\n${t}`:'Üç seçimi tamamla; ardından kendi raporunu yaz. / Complete the three choices, then write your report.'}
['#conclusion','#reason','#limitation','#ownSentence'].forEach(id=>$(id).addEventListener('input',updatePreview));
$('#finish').onclick=()=>{const c=$('#conclusion').value,r=$('#reason').value,l=$('#limitation').value,t=$('#ownSentence').value.trim();if(!c||!r||!l)return feedback('#reportFeedback',false,'Önce üç seçim alanını tamamla. / Complete all three choices.');if(!c.startsWith('Kanıtlara')||!r.startsWith('görev')||!l.startsWith('ancak'))return feedback('#reportFeedback',false,'Seçimlerini yeniden incele. Elif hakkında yorum var; kamera ise sarı etiketi göstermiyor. / Revisit the evidence and the uncertainty.');if(!t)return feedback('#reportFeedback',false,'Kendi raporunu yaz. Cümle başlangıçlarından yardım alabilirsin. / Write your report using the sentence starters if needed.');if(![...$$('#reportChecks input')].every(x=>x.checked))return feedback('#reportFeedback',false,'Raporunu okuyup üç kontrol kutusunu işaretle. Eksik varsa önce metnini tamamla. / Review your report and complete the checklist.');updatePreview();add(20,'report');$('#finalScore').textContent=score;$('#submittedReport').textContent=t;$('#reportWork').classList.add('hidden');$('#result').classList.remove('hidden');$('#result').scrollIntoView({behavior:'smooth'})};
$('#editReport').onclick=()=>{$('#reportWork').classList.remove('hidden');$('#result').classList.add('hidden')};
$('#ownSentence').addEventListener('input',()=>{$$('#reportChecks input').forEach(x=>x.checked=false)});
