const S=[...document.querySelectorAll('.stage')],T=[...document.querySelectorAll('.map button')];let unlocked=0;
function show(n){if(n>unlocked)return;S.forEach((s,i)=>s.classList.toggle('active',i===n));T.forEach((t,i)=>{t.classList.toggle('active',i===n);t.disabled=i>unlocked;t.setAttribute('aria-current',i===n?'step':'false')});document.querySelector('#game').scrollIntoView({behavior:'smooth'})}
document.querySelector('#start').onclick=()=>{document.querySelector('#intro').hidden=true;document.querySelector('#game').hidden=false;show(0)};
T.forEach((b,i)=>{b.disabled=i>0;b.onclick=()=>show(i)});
function fb(i,ok,msg){const f=S[i].querySelector('.feedback');f.className='feedback show '+(ok?'good':'bad');f.textContent=msg}
for(let i=0;i<2;i++){const b=document.createElement('button');b.className='continue-stage';b.type='button';b.hidden=true;b.textContent='Açıklamayı okudum · Devam et / Continue →';b.onclick=()=>show(i+1);S[i].querySelector('.feedback').after(b)}
document.querySelectorAll('.opt').forEach(b=>{b.setAttribute('aria-pressed','false');b.onclick=()=>{b.parentElement.querySelectorAll('.opt').forEach(x=>{x.classList.remove('sel');x.setAttribute('aria-pressed','false')});b.classList.add('sel');b.setAttribute('aria-pressed','true');const stage=b.closest('.stage');stage.querySelector('.feedback').className='feedback';stage.querySelector('.continue-stage').hidden=true}});
function unlock(i){unlocked=Math.max(unlocked,i+1);T.forEach((b,j)=>b.disabled=j>unlocked);S[i].querySelector('.continue-stage').hidden=false}
S[0].querySelector('.next').onclick=()=>{const selected=S[0].querySelector('.sel');if(!selected)return fb(0,false,'Önce bir plan seç. / Select a plan first.');if(!selected.dataset.ok)return fb(0,false,'Bütçe en fazla 40.000 TL. Daha yüksek tutarı bul. / Find the cost above 40,000 TL.');fb(0,true,'A planı bütçeyi 5.000 TL aşıyor ve yağmura uygun değil. B ve C bütçeye uyuyor; ikisi de kapalı salonda yapılabilir. / A is over budget by 5,000 TL. B and C meet the budget and indoor requirements.');unlock(0)};
S[1].querySelector('.next').onclick=()=>{const qs=[...S[1].querySelectorAll('.q')],missing=qs.findIndex(q=>!q.querySelector('.sel'));if(missing>=0)return fb(1,false,`${missing+1}. soruda bir cevap seç. / Select an answer for question ${missing+1}.`);const wrong=qs.map((q,i)=>q.querySelector('.sel').dataset.ok?null:i+1).filter(Boolean);if(wrong.length)return fb(1,false,`${wrong.join(', ')}. soruyu yeniden düşün. Yukarıdaki plan bilgilerine bak. / Revisit question(s) ${wrong.join(', ')} using the plan reference above.`);fb(1,true,'B planı 8.000 TL daha ucuz. C planına 40 kişi daha fazla katılabilir. İkisi de 230 kişilik salona sığıyor. Bu yüzden seçim, önceliğine bağlı. / B costs less; C serves more students. Both fit in the hall.');unlock(1)};
const examples={B:'Bence Oyun ve Spor uygun çünkü 30.000 TL tutuyor. Sanat ve Teknoloji planından 8.000 TL daha ucuz. Ama bu plana 40 kişi daha az katılabilir. Bu yüzden kalan parayla başka okul etkinlikleri yapmak istiyorum.',C:'Bence Sanat ve Teknoloji uygun çünkü 220 kişi katılabilir. Bu plana Oyun ve Spor planından 40 kişi daha fazla katılabilir. Ama 8.000 TL daha pahalı. Bu yüzden bu festivalde daha çok öğrenciye yer vermek istiyorum.'};
S[2].querySelector('.next').onclick=()=>{const plan=document.querySelector('input[name=finalPlan]:checked')?.value,t=document.querySelector('#decision').value.trim();if(!plan)return fb(2,false,'Önce B veya C planını seç. / Choose B or C first.');if(!t)return fb(2,false,'Kararını birkaç cümleyle yaz. Cümle başlangıçlarından yardım al. / Write your decision; use the sentence starters for help.');if(![...document.querySelectorAll('#decisionChecks input')].every(x=>x.checked))return fb(2,false,'Metnini okuyup kontrol kutularını tamamla. Eksik varsa önce metnini düzelt. / Review your text and complete the checklist.');fb(2,true,'Kararın hazır. Bu bir dil sınavı değil; örnekle karşılaştır ve gerekçeni arkadaşınla veya öğretmeninle tartış. / Compare with the example and discuss your reasoning.');document.querySelector('#chosen').textContent=(plan==='B'?'B · Oyun ve Spor':'C · Sanat ve Teknoloji')+' planını seçtin. / Your chosen plan.';document.querySelector('#submittedDecision').textContent=t;document.querySelector('#decisionModel').textContent=examples[plan];document.querySelector('.result').classList.add('show');document.querySelector('.result').scrollIntoView({behavior:'smooth'})};
function invalidate(){document.querySelector('.result').classList.remove('show');S[2].querySelector('.feedback').className='feedback';document.querySelectorAll('#decisionChecks input').forEach(x=>x.checked=false)}
document.querySelector('#decision').addEventListener('input',invalidate);document.querySelectorAll('[name=finalPlan]').forEach(x=>x.addEventListener('change',invalidate));
